{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Data\",\"dCalendar\",\"Measuresss\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "5fa35cef-2171-4e81-8d10-e0a8b426ef32",
        "fromColumn": "Date",
        "fromTable": "dCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f0899106-768a-4a30-a66e-12b716478bb0"
      },
      {
        "name": "448a671d-dc9b-46d5-a9eb-545a85ed81d4",
        "fromColumn": "StartMonth",
        "fromTable": "dCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4d211e95-c02e-435b-a50c-76eb08edde61"
      },
      {
        "name": "04fa3925-e2f3-ae15-eba7-97c894f092ee",
        "fromColumn": "Order Date",
        "fromTable": "Data",
        "toColumn": "Date",
        "toTable": "dCalendar"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e105ad34-bf41-4ff2-bcc3-f30df5063a2d",
            "sourceColumn": "Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3e05cc28-22a2-48a5-ab70-f3c832513f1c",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6feffd5-2671-432c-9a9f-6cd4533ab548",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d3225de-c573-4825-a463-d84a66bdbec7",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buyer Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b4dac55-441b-40cc-929b-406847caffc0",
            "sourceColumn": "Buyer Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Buyer Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6144db0-2e84-4846-9927-adc554d87d98",
            "sourceColumn": "Buyer Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "d0c740da-7944-486a-9202-066feee7ead5",
            "sourceColumn": "Order Location",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b002b0c3-1d27-4334-9a89-eef9d7f45397",
            "sourceColumn": "Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9902aa3-7b7a-4295-9c41-5fe14d297213",
            "sourceColumn": "Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "International Shipping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62cc2811-664a-434e-a2c9-3e44df23f09c",
            "sourceColumn": "International Shipping",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68904862-9ca3-4f18-a31a-e57a9079b7ad",
            "sourceColumn": "Sales Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping Charges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "48b7c335-5924-4bca-8c2e-c5c7ebf19117",
            "sourceColumn": "Shipping Charges",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b71cba93-bb98-487a-bde7-0e8f51ecb7e0",
            "sourceColumn": "Sales per Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec4e8744-fcc3-47a0-8cee-d846364822c1",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "504c5b5f-2b0b-4369-9c7e-52cb73c150c0",
            "sourceColumn": "Total Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f84d90e4-ff21-4c18-a3fb-a5be8d8c5ce3",
            "sourceColumn": "Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd887f26-8319-4d0b-bac2-a87e7c406bd3",
            "sourceColumn": "Review",
            "summarizeBy": "none"
          },
          {
            "name": "Age Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1495914-8d58-4c27-9eb9-ec7b426da4f5",
            "sourceColumn": "Age Group",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    Data[Order Location] = \"Austin\", \"US\",",
              "    Data[Order Location] = \"Cardiff\", \"Europe\",",
              "    Data[Order Location] = \"Cleveland\", \"US\",",
              "    Data[Order Location] = \"Detroit\", \"US\",",
              "    Data[Order Location] = \"Dublin\", \"Europe\",",
              "   Data[Order Location] = \"Glasgow\", \"Europe\",",
              "    Data[Order Location] = \"Las Vegas\", \"US\",",
              "    Data[Order Location] = \"Liverpool\", \"Europe\",",
              "    Data[Order Location] = \"London\", \"Europe\",",
              "    Data[Order Location] = \"Manchester\", \"Europe\",",
              "    Data[Order Location] = \"Memphis\", \"US\",",
              "    Data[Order Location] = \"Miami\", \"US\",",
              "    Data[Order Location] = \"Montreal\", \"Canada\",",
              "    Data[Order Location] = \"Mumbai\", \"India\",",
              "    Data[Order Location] = \"New Delhi\", \"India\",",
              "    Data[Order Location] = \"New Jersey\", \"US\",",
              "    Data[Order Location] = \"New York\", \"US\",",
              "    Data[Order Location] = \"Paris\", \"Europe\",",
              "    Data[Order Location] = \"Pittsburgh\", \"US\",",
              "    Data[Order Location] = \"Portland\", \"US\",",
              "    Data[Order Location] = \"Sacramento\", \"US\",",
              "    Data[Order Location] = \"San Antonio\", \"US\",",
              "    Data[Order Location] = \"San Francisco\", \"US\",",
              "    Data[Order Location] = \"Sydney\", \"Australia\",",
              "    Data[Order Location] = \"Toronto\", \"Canada\",",
              "    \"Others\"  -- Default value if no match",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f0328935-c7a1-47ac-8fe7-67bfe09e33ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "National Shipping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab5b02fb-d5b8-4ac6-a7de-c658e08d57cb",
            "sourceColumn": "National Shipping",
            "summarizeBy": "none"
          },
          {
            "name": "Locations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b3e6fe-9ec9-4014-90e4-849f6827ec38",
            "sourceColumn": "Locations",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cf943c8a-8f18-47d7-b6ac-43b706e76638",
        "partitions": [
          {
            "name": "Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\W4rne4\\Music\\Musics\\Downloads\\Onyx Data -DataDNA Dataset Challenge - Merchandise Sales Dataset - January 2025\\Onyx Data -DataDNA Dataset Challenge - Merchandise Sales Dataset - January 2025.xlsx\"), null, true),",
                "    Data_Sheet = Source{[Item=\"Data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order ID\", Int64.Type}, {\"Order Date\", type date}, {\"Product Category\", type text}, {\"Buyer Gender\", type text}, {\"Buyer Age\", Int64.Type}, {\"Order Location\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"International Shipping\", type text}, {\"Sales Price\", Int64.Type}, {\"Shipping Charges\", Int64.Type}, {\"Sales per Unit\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"Total Sales\", Int64.Type}, {\"Rating\", Int64.Type}, {\"Review\", type text}}),",
                "    #\"Inserted Range1\" = Table.AddColumn(#\"Changed Type\", \"Range\", each let rangeSize = 3, offset = 0, inclusive = true, rangeIndex = Number.RoundDown(([Buyer Age] - offset) / rangeSize) in Text.From(rangeIndex * rangeSize + offset, \"pt-BR\") & \"-\" & Text.From((rangeIndex + 1) * rangeSize + offset - (if inclusive then 1 else 0), \"pt-BR\"), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Range1\",{{\"Range\", \"Age Group\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Rating\", \"Rating - Copy\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"Rating - Copy\", type text}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Changed Type1\", \"International Shipping\", \"International Shipping - Copy\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Duplicated Column1\",{\"Rating - Copy\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"International Shipping - Copy\", \"National Shipping\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"No\",\"National\",Replacer.ReplaceText,{\"National Shipping\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Yes\",\"International\",Replacer.ReplaceText,{\"National Shipping\"}),",
                "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Replaced Value1\", \"Order Location\", \"Order Location - Copy\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column2\",{{\"Order Location - Copy\", \"Locations\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_04969253-f40b-4791-9ccb-b87fe3ce8b06",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aaa8cc62-58c6-41ea-9e7b-dcbb43299143",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8970bd6a-5280-482c-b1c8-5d9e8a59fc93",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0368e180-8006-459d-b5e5-41393068dd6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0e8c342e-ab47-46af-b013-8ae0136c965b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c996bbeb-b7d4-43f4-a895-8bb1e21540f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "41f8c681-695b-4b6c-b2a1-7d9c389a21db",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "59fbe240-5593-4379-8c3f-812689657cf4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bd138743-5e81-4d8c-8d00-775a0e21d558",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5e07278b-c652-41f4-9267-3edfbd608f33",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "44667e86-72f0-4463-8059-eea451c0e906",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "97af45b5-2f03-4a07-a08e-247c63cf4851",
                "ordinal": 3
              }
            ],
            "lineageTag": "e6fad693-0b30-4aac-9e6f-751ad9d7eebe"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9c1b89ac-2fef-4600-b9d7-caa7e912c3c7",
        "partitions": [
          {
            "name": "DateTableTemplate_04969253-f40b-4791-9ccb-b87fe3ce8b06",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d80a5884-36c1-401b-93db-947cf75c8e3c",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f0899106-768a-4a30-a66e-12b716478bb0"
                },
                "isDefault": true,
                "relationship": "5fa35cef-2171-4e81-8d10-e0a8b426ef32"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce80857b-aa0f-44f5-83e9-ee7f5022ce94",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "51d238e5-780d-4389-bcd5-cb19e9592a4e",
            "sortByColumn": "MonthNum",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthAbbre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "93775b6a-37c6-4217-b520-da8606c4d06a",
            "sortByColumn": "MonthNum",
            "sourceColumn": "MonthAbbre",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f081589a-87af-4f44-939b-4e88f5b127ce",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b8141561-5d34-4f82-a560-37279a87d884",
            "sourceColumn": "MonthNum",
            "summarizeBy": "sum"
          },
          {
            "name": "yearMonthINT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cfc73d1b-b612-4278-874f-49a423ecef18",
            "sourceColumn": "yearMonthINT",
            "summarizeBy": "sum"
          },
          {
            "name": "StartMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ec5b9691-76c9-47a4-98d3-0dbb17ab6a97",
            "sourceColumn": "StartMonth",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4d211e95-c02e-435b-a50c-76eb08edde61"
                },
                "isDefault": true,
                "relationship": "448a671d-dc9b-46d5-a9eb-545a85ed81d4"
              }
            ]
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b830c9f-19f9-4b9e-b47a-94c98c4f4f78",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarterAbbre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71081614-0434-44a8-916a-6a05b6753bd1",
            "sourceColumn": "QuarterAbbre",
            "summarizeBy": "none"
          },
          {
            "name": "Bimestrer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07a20784-4616-4fb8-9aac-02035f8657f1",
            "sourceColumn": "Bimestrer",
            "summarizeBy": "none"
          },
          {
            "name": "Semestrer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dda24b03-aff7-4a6a-95f3-c249ff6abf8f",
            "sourceColumn": "Semestrer",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7740999-1f92-43fb-9877-b6832c6d6ac9",
            "sourceColumn": "Week",
            "summarizeBy": "sum"
          },
          {
            "name": "DayWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ecfc7c6-c000-419d-8368-2e10e3917836",
            "sourceColumn": "DayWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "NameDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42abc09c-4b2f-48b3-8cac-e32d42bdae79",
            "sourceColumn": "NameDay",
            "summarizeBy": "none"
          },
          {
            "name": "Past",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4dba1c52-590b-4f3a-9c62-1e1ae277498a",
            "sourceColumn": "Past",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f99107c1-f08d-4f5f-9859-c3fbd71371ad",
            "sourceColumn": "CurrentYear",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c6bb232-593d-4552-8714-3e18451189e9",
            "sourceColumn": "CurrentMonth",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0d795387-3819-458a-8c0f-24b32d26b522",
        "partitions": [
          {
            "name": "dCalendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "//Alterar somente a Tabela e a coluna de datas",
                "/* A Tabela  onde possui uma coluna Data que deseja usar em seus clculos ou visuais. ",
                "Exemplo. Tabela fVendas que possui a coluna Data Pedido Ficaria List.Min (fVendas[Data Pedido]).",
                "Se Possuir mais de uma coluna ficaria List.Min (fVendas[Data Pedido] & fVendas[Data Vencimento]).",
                "*/",
                "",
                "    MenorData = List.Min (Data[Order Date]),",
                "    MaiorData = List.Max (Data[Order Date]),",
                "\t",
                "//No alterar daqui pra baixo\t",
                "\t",
                "    DataInicio = Date.StartOfYear(MenorData),",
                "    DataFim = Date.EndOfYear(MaiorData),",
                "    Dias = Duration.Days(DataFim- DataInicio) +1,",
                "    ListarDatas = List.Dates(DataInicio, Dias, #duration(1,0,0,0)),",
                "    Tabela = #table(",
                "        type table[",
                "            Date = date,",
                "            Year = Int64.Type,",
                "            MonthName = text,",
                "            MonthAbbre = text,",
                "            MonthYear = text,",
                "            MonthNum = number,",
                "            yearMonthINT = number,",
                "            StartMonth = date,",
                "            Quarter = Int64.Type,",
                "            QuarterAbbre = text,",
                "            Bimestrer = text,",
                "            Semestrer = text,",
                "            Week = Int64.Type,",
                "            DayWeek = Int64.Type,",
                "            NameDay = text,",
                "            Past = logical,",
                "            CurrentYear = text,",
                "            CurrentMonth = text",
                "        ],",
                "        List.Transform(",
                "            ListarDatas,",
                "            each {",
                "                _,",
                "                Date.Year(_),",
                "                Text.Proper( Date.MonthName(_)),",
                "                Text.Proper(Text.Start(Date.MonthName(_), 3)),",
                "                Text.Proper(Text.Start(Date.MonthName(_), 3)) & \"-\" & Text.End(Text.From(Date.Year(_)), 2),",
                "                Date.Month(_),",
                "                Date.Year(_) * 100 + Date.Month(_),",
                "                Date.StartOfMonth(_),",
                "                Date.QuarterOfYear(_),",
                "                Text.From(Date.QuarterOfYear(_)) & \"Q\",",
                "                Text.From( Number.RoundUp( Date.Month(_)/2,0)) & \" Bim\",",
                "                Text.From( Number.RoundUp( Date.Month(_)/6,0)) & \" Sem\",",
                "                Date.WeekOfMonth(_),",
                "                Date.DayOfWeek(_),",
                "                Date.DayOfWeekName(_),",
                "                if _ <= MaiorData then true else false,",
                "                if Date.IsInCurrentYear(_) then \"Current Year\" else Text.From(Date.Year(_)),",
                "                if Date.IsInCurrentYear(_) and Date.IsInCurrentMonth(_) then \"Current Month\" else Text.Proper( Date.MonthName(_))",
                "            }",
                "",
                "        )",
                "    ),",
                "    #\"Replaced Value\" = Table.ReplaceValue(Tabela,\"Fev\",\"Feb\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Abr\",\"Apr\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Mai\",\"May\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Ago\",\"Aug\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Set\",\"Sept\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Out\",\"Oct\",Replacer.ReplaceText,{\"MonthAbbre\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Dez\",\"Dec\",Replacer.ReplaceText,{\"MonthAbbre\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f0899106-768a-4a30-a66e-12b716478bb0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7ae5433f-a908-4c5f-95ef-13d81df42cdf",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "693863e3-e956-48aa-ab67-2588f40940ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b8ce2c9e-02c5-4ffe-9790-bc8a671d7317",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "79824830-64a1-42b7-ac8a-49fb09e9568d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e1181b0c-56b6-47ad-80d0-7afbaf2c0df3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "da5f29a4-68c3-456f-8aab-09a2e4fe960f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b4f2de61-787e-48a6-9b31-a163597cb52d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cdfd9263-93b5-4b1c-8549-dac134b5a1fd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7ba4664f-6200-4c27-b4dd-42a2dd48d197",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b85997ab-7a5e-432a-80f5-6dbdc39f41dd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fe59b1e5-0d78-4212-b6b7-80ff0da7d2e2",
                "ordinal": 3
              }
            ],
            "lineageTag": "0bf12f64-6af5-42e4-b2b8-6c3a5d89d97d"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5c8e92f-2d1c-4ae9-852a-dad2823d8182",
        "partitions": [
          {
            "name": "LocalDateTable_f0899106-768a-4a30-a66e-12b716478bb0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendar'[Date])), 1, 1), Date(Year(MAX('dCalendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4d211e95-c02e-435b-a50c-76eb08edde61",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bb81253f-03d9-464a-81e2-44f4b738ef63",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "91b6ddba-13e4-4d9b-9368-11f651c11c9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ba9b11c1-9819-4169-9349-4531bc614e6b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e188e6b3-b778-4afd-be1a-2f0c41f691e5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2a0b0b75-42ed-4d9d-8af0-99b8922a15c1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3895bd48-2b70-42f7-a25f-f3187137f2e2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fa63a72b-bf36-4342-8847-771af30eb7f1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b30898db-0d30-4092-827e-b09e12f2892f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1b6c21b7-9aef-4e69-8a87-f44e800666c9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "92def8d3-e2e6-4058-8cc0-8b20b9e8f181",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "381e1a7f-2e2a-458d-ae8f-153933665637",
                "ordinal": 3
              }
            ],
            "lineageTag": "75fd2b63-7c3b-46e3-b7c2-ee324161227f"
          }
        ],
        "isHidden": true,
        "lineageTag": "6c82e308-ea21-456d-a63d-68dcd3c88d82",
        "partitions": [
          {
            "name": "LocalDateTable_4d211e95-c02e-435b-a50c-76eb08edde61",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendar'[StartMonth])), 1, 1), Date(Year(MAX('dCalendar'[StartMonth])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Measuresss",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "445d4699-f729-4cb2-98df-4f24b433a016",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9ff20ceb-7486-487f-9434-c5dbbc73301a",
        "measures": [
          {
            "name": "$ Total Sales",
            "displayFolder": "$ Values",
            "expression": "Sum(Data[Total Sales])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "bad905fd-7973-471c-9e2b-e040b80d272b"
          },
          {
            "name": "@ Placeholder",
            "displayFolder": "UI/UX",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "949556a9-f675-42be-8785-82d58ec1e8f3"
          },
          {
            "name": "@ BarChart IDProdFat",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "",
              "VAR _itemname = SELECTEDVALUE(Data[Product ID])",
              "",
              "VAR _Value =FORMAT([$ Total Sales], \"$ #\")",
              "VAR _indicator =FORMAT([% Sales LM],\" 0.0% PM; 0.0% PM\") //  - \"0.0% YoY\"",
              "VAR _acumulado =FORMAT([# Qty Sold],\" #; (#)\")// - \" #0, K; (#0, K) decimal #.0\"",
              "VAR _Label = _itemname & \" | \" & _Value & \" | \" & _acumulado & \" | \" & _indicator",
              "",
              "RETURN",
              "_Label"
            ],
            "lineageTag": "e6139989-cd67-4658-989e-84f269833e46"
          },
          {
            "name": "# LM Inter Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE (",
              "    [$ International Sales],",
              "    PREVIOUSMONTH ( dCalendar[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d8e550a9-26f0-42c6-a29d-d6563189b440"
          },
          {
            "name": "# LM Total Sales",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Total Sales]), PREVIOUSMONTH(dCalendar[Date]))",
            "formatString": "0",
            "lineageTag": "4e48fd05-e4f1-406b-8bfc-2eef026fce97"
          },
          {
            "name": "% Sales LM",
            "displayFolder": "% Percentage",
            "expression": "DIVIDE([$ Total Sales] - [# LM Total Sales],[# LM Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0224866a-60e0-468a-94ab-15c4be079701"
          },
          {
            "name": "@ Color Rotulo",
            "displayFolder": "UI/UX",
            "expression": "IF([% Sales LM] > 0, \"#000000\", \"#FA8187\")",
            "lineageTag": "17f3d494-1371-497c-984f-c2b74ddd86a2"
          },
          {
            "name": "@ min_max color",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Total Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Total Sales])",
              "    RETURN",
              "    IF([$ Total Sales] = min_val, \"#FF4A4A\",",
              "       if([$ Total Sales] = max_val,\"#68DA52\",\"#CCCCCC\"))"
            ],
            "lineageTag": "3cad0a0b-fa11-40aa-a69f-9916da13873a"
          },
          {
            "name": "# Qty Sold",
            "displayFolder": "# Numbers",
            "expression": "SUM(Data[Quantity])",
            "formatString": "0",
            "lineageTag": "b5bcf576-8171-45ce-8b4f-2023170bc262"
          },
          {
            "name": "$ Sales LY",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE([$ Total Sales],SAMEPERIODLASTYEAR(dCalendar[Date]))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "61b19d64-7a08-4913-841e-e905ee7bdfb7"
          },
          {
            "name": "@ Cor COndicional",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales % Change] >0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "5ceb0277-e628-4c63-93fc-aff11ab9e9ff"
          },
          {
            "name": "JSON",
            "expression": "TOJSON(Data, 10) ",
            "lineageTag": "a4ed5b84-c57c-414f-b572-96aad45ba877"
          },
          {
            "name": "# Avg. Rating",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "# Numbers",
            "expression": "AVERAGEX(Data,Data[Rating])",
            "lineageTag": "413cbddd-2b9f-4160-aafb-8e7912dfe4a9"
          },
          {
            "name": "Sales by Month",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( Data[Total Sales] ),",
              "    RELATEDTABLE(dCalendar),",
              "    FILTER (",
              "        dCalendar,",
              "        dCalendar[Date] = EOMONTH(dCalendar[Date],0) ",
              "    )",
              "",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "57ae5a2a-d002-43dc-8606-15951dc6ff82"
          },
          {
            "name": "Sales by Category",
            "expression": "CALCULATE([$ Total Sales], ALLEXCEPT('Data', 'Data'[Product Category]))",
            "formatString": "0",
            "lineageTag": "468959c1-29ba-4553-92a4-ab4fca988298"
          },
          {
            "name": "Sales by Location",
            "expression": "CALCULATE([$ Total Sales], ALLEXCEPT('Data', 'Data'[Order Location]))",
            "formatString": "0",
            "lineageTag": "a2c9be50-bc0c-4f51-ae4d-2327c00bb589"
          },
          {
            "name": "Average Shipping Charge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE('Data'[Shipping Charges]),",
              "    'Data'[International Shipping] = \"Yes\"",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c3f688ba-ad20-4575-9774-cb7a5cf28c0b"
          },
          {
            "name": "$ Shipping Charges",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "$ Values",
            "expression": "SUM('Data'[Shipping Charges])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e2f353ab-4191-4e1f-9b5e-4ab9b80390f7"
          },
          {
            "name": "Average International Shipping Charge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE('Data'[Shipping Charges]),",
              "    FILTER(",
              "        'Data',",
              "        'Data'[International Shipping] = \"Yes\"",
              "    )",
              ")"
            ],
            "lineageTag": "6b415100-5685-4273-be3f-e2cc63287961"
          },
          {
            "name": "% of Total Sales",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "DIVIDE(",
              "    [$ Total Sales],",
              "    CALCULATE(",
              "        [$ Total Sales],",
              "        ALL(Data)",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bec444c4-950d-4f86-bae7-c83463261309"
          },
          {
            "name": "Most Popular Product",
            "expression": [
              "",
              "VAR BestProduct =",
              "    TOPN(",
              "        1, ",
              "        VALUES('Data'[Product ID]), ",
              "        [$ Total Sales], ",
              "        DESC",
              "    )",
              "RETURN",
              "    CONCATENATEX(",
              "        BestProduct, ",
              "        'Data'[Product ID], ",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "dddecc9a-ceea-4fd3-b71b-16d96745b1d6"
          },
          {
            "name": "Buyer Count",
            "expression": "DISTINCTCOUNT('Data'[Order ID])",
            "formatString": "0",
            "lineageTag": "98841055-938e-4730-96bc-816a7ae952d3"
          },
          {
            "name": "% of Buyers by Gender",
            "displayFolder": "% Percentage",
            "expression": "DIVIDE(CALCULATE([Buyer Count], ALLEXCEPT('Data', 'Data'[Buyer Gender])), [Buyer Count])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "db1df6b6-5367-47ab-9ced-278f70dcfc51"
          },
          {
            "name": "% of Buyers by Age Group",
            "displayFolder": "% Percentage",
            "expression": "DIVIDE(CALCULATE([Buyer Count], FILTER('Data', 'Data'[Buyer Age] >= 18 && 'Data'[Buyer Age] < 25)), [Buyer Count])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "9d0864ee-0c23-465a-8142-30ed6d91a989"
          },
          {
            "name": "$ Sales Ship Reduction x%",
            "displayFolder": "$ Values",
            "expression": "[$ Shipping Charges] * (1 - [% Shiping Reduction Value])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9d085593-60a9-4144-853c-d82f56a21705"
          },
          {
            "name": "# LM Quantity",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX(Data,Data[Quantity]),",
              "    PREVIOUSMONTH ( dCalendar[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c8670508-d4f3-43ae-ba11-7edfe423cea4"
          },
          {
            "name": "@ Color Rotulo New",
            "displayFolder": "UI/UX",
            "expression": "IF([# LM Inter Sales]> [# LM Inter Sales], \"#000000\", \"#FA8187\")",
            "lineageTag": "82ebce05-a42b-412e-8933-088d5c81dae9"
          },
          {
            "name": "$ Saving Ship Changes",
            "displayFolder": "$ Values",
            "expression": "[$ Shipping Charges] - [$ Sales Ship Reduction x%]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e9cd9eab-ed2b-423c-9fc9-b76087939388"
          },
          {
            "name": "$ Total Sales YTD",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "TOTALYTD(",
              "    [$ Total Sales], ",
              "    dCalendar[Date]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4f2eb8f8-8b99-4701-a924-71ebcc4cc290"
          },
          {
            "name": "Unique Ratings Text",
            "expression": [
              "",
              "CONCATENATEX(",
              "    DISTINCT(Data[Rating]), ",
              "    Data[Rating], ",
              "    \", \"",
              ")"
            ],
            "lineageTag": "99b1bae9-a903-4f98-a8ec-00c44ef58200"
          },
          {
            "name": "# Orders",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "# Numbers",
            "expression": "DISTINCTCOUNT(Data[Order ID])",
            "formatString": "0",
            "lineageTag": "df5ace2f-b65d-455f-9340-2ea2855a7241"
          },
          {
            "name": "$ International Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[International Shipping] = \"Yes\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9bfb3e0a-dc6c-41ba-8f9e-dbf7f883068f"
          },
          {
            "name": "@ BarChart Location",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "",
              "VAR _itemname = SELECTEDVALUE(Data[Order Location])",
              "",
              "VAR _Value =FORMAT([$ Total Sales], \"$ #\")",
              "VAR _indicator =FORMAT([% Sales LM],\" 0.0% PM; 0.0% PM\") //  - \"0.0% YoY\"",
              "VAR _acumulado =FORMAT([# Qty Sold],\" #; (#)\")// - \" #0, K; (#0, K) decimal #.0\"",
              "VAR _Label = _itemname & \" | \" & _Value & \" | \" & _acumulado & \" | \" & _indicator",
              "",
              "RETURN",
              "_Label"
            ],
            "lineageTag": "0f84c785-0525-47c2-8096-fd07077ec24e"
          },
          {
            "name": "@ BarChart regions",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "",
              "VAR _itemname = SELECTEDVALUE(Data[Region])",
              "",
              "VAR _Value =FORMAT([$ Total Sales], \"$ #,##0,.0 K\")",
              "VAR _indicator =FORMAT([# Qty Sold],\" #; (#)\") //  - \"0.0% YoY\"",
              "VAR _indicator2 =FORMAT([% Sales LM],\" 0.0% PM; 0.0% PM\")",
              "VAR _Label = _itemname & \" | \" & _Value & \" | \" & _indicator & \" | \" & _indicator2",
              "",
              "RETURN",
              "_Label"
            ],
            "lineageTag": "000b51c9-9e17-4e66-8317-514a4416c797"
          },
          {
            "name": "$ US Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[Region] = \"US\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "4a27c609-59ab-48a3-ac50-0063f65623ed"
          },
          {
            "name": "$ India Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[Region] = \"India\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "840499bb-175b-4d44-96b8-0ac52e86d80d"
          },
          {
            "name": "$ Europe Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[Region] = \"Europe\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "431f0d2e-4495-4b6e-8771-637d40f31f19"
          },
          {
            "name": "$ Canada Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[Region] = \"Canada\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "7f164363-e12b-4aab-a49d-cd908be7e3a1"
          },
          {
            "name": "$ Australia Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[Region] = \"Australia\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "d62f3f63-4589-4327-9599-4209cd1b1a6d"
          },
          {
            "name": "@ min_max color AUstralia",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Australia Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Australia Sales])",
              "    RETURN",
              "    IF([$ Australia Sales] = min_val, \"#FF2C2C\",",
              "       if([$ Australia Sales] = max_val,\"#00ff00\",\"#CCCCCC\"))"
            ],
            "lineageTag": "aa78f949-b462-44d0-b1f7-01c17213e1e3"
          },
          {
            "name": "@ min_max color Canada",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Canada Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Canada Sales])",
              "    RETURN",
              "    IF([$ Canada Sales] = min_val, \"#FF2C2C\",",
              "       if([$ Canada Sales] = max_val,\"#00ff00\",\"#CCCCCC\"))"
            ],
            "lineageTag": "0d14e3e6-a792-43d0-8298-302b79deac28"
          },
          {
            "name": "@ min_max color India",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ India Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ India Sales])",
              "    RETURN",
              "    IF([$ India Sales] = min_val, \"#FF2C2C\",",
              "       if([$ India Sales] = max_val,\"#00ff00\",\"#CCCCCC\"))"
            ],
            "lineageTag": "d5e0fd71-439d-4cb6-9b16-e3b6bf8a2559"
          },
          {
            "name": "@ min_max color Europe",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Europe Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ Europe Sales])",
              "    RETURN",
              "    IF([$ Europe Sales] = min_val, \"#FF2C2C\",",
              "       if([$ Europe Sales] = max_val,\"#00ff00\",\"#CCCCCC\"))"
            ],
            "lineageTag": "c567bb28-49ce-4c6e-b513-7ed3a30b3593"
          },
          {
            "name": "@ min_max color USA",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "    VAR max_val = MAXX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ US Sales])",
              "    VAR min_val = MINX( ALLSELECTED(dCalendar[MonthAbbre],dCalendar[MonthNum]),[$ US Sales])",
              "    RETURN",
              "    IF([$ US Sales] = min_val, \"#FF2C2C\",",
              "       if([$ US Sales] = max_val,\"#00ff00\",\"#CCCCCC\"))"
            ],
            "lineageTag": "205654df-eb06-4789-8bb4-6d58cb5a72a8"
          },
          {
            "name": "# Inter Orders Buyer Count",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[International Shipping] = \"Yes\"",
              ")",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "1f559001-556a-4e36-ab07-3957304ce30e"
          },
          {
            "name": "# Current Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Data[Total Sales]),",
              "    dCalendar[Year] = 2024,",
              "    dCalendar[MonthName] = \"Novembro\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "5c7276de-0fda-45dd-896c-f5babf0f5046"
          },
          {
            "name": "# Internatiol Current Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ International Sales],",
              "    dCalendar[Year] = 2024,",
              "    dCalendar[MonthName] = \"Novembro\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "1f3808f7-0779-43a7-a291-3b9d162db2f0"
          },
          {
            "name": "@ total orders",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "FORMAT( [# Orders] , \"#\")"
            ],
            "lineageTag": "cc21902a-34fa-40e4-8bd2-1aadbc9d95b0"
          },
          {
            "name": "# Disconts",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUMX(Data,Data[Sales per Unit] * Data[Quantity] - Data[Total Sales]))",
            "formatString": "0",
            "lineageTag": "37f1af55-cddc-496c-887b-766d2fb220be"
          },
          {
            "name": "# US Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[Region] = \"US\"",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "af5246d9-c86d-4d11-88be-b86c3ce62604"
          },
          {
            "name": "# US Current Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ US Sales],",
              "    dCalendar[Year] = 2024,",
              "    dCalendar[MonthName] = \"Novembro\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5796afcd-ae27-4619-83a4-b91a1092d156"
          },
          {
            "name": "# Europe Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[Region] = \"Europe\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "94d6e958-4503-47db-ac22-7498e60f5153"
          },
          {
            "name": "# India Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[Region] = \"India\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "db346d5d-03f4-45de-a0b7-9987190c566f"
          },
          {
            "name": "# Canada Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[Region] = \"Canada\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bee5e573-a70d-4e05-ad2b-212d5440b9c2"
          },
          {
            "name": "# Australia Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT('Data'[Order ID]), ",
              "    Data[Region] = \"Australia\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fd5b9e21-6875-40a2-8506-763055eaa30f"
          },
          {
            "name": "# Shipping Charger",
            "displayFolder": "# Numbers",
            "expression": "DISTINCT(Data[Shipping Charges])",
            "formatString": "0",
            "lineageTag": "ed0a449a-7bbe-4e6f-9623-a5a26943fc96"
          },
          {
            "name": "% Sales PM",
            "displayFolder": "% Percentage",
            "expression": "DIVIDE([$ Total Sales] - [Past Month],[Past Month])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f12cc7cf-b1cd-44d7-bebe-1fa79b71c172"
          },
          {
            "name": "Past Year",
            "expression": [
              "",
              "    CALCULATE([$ Total Sales],",
              "        DATEADD(dCalendar[Date],",
              "        -1,",
              "        YEAR))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fbd4ca8d-92f9-45c5-b205-ad77126debc0"
          },
          {
            "name": "% MoM Sales USA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonth = ",
              "    CALCULATE(",
              "        MAX(dCalendar[Date]),",
              "        ALL(dCalendar)  // Ignore any existing filters on the dCalendar table",
              "    )  // Dynamically get the latest date in the model",
              "",
              "VAR CurrentMonthSales = ",
              "    CALCULATE(",
              "        [$ US Sales],",
              "        dCalendar[Date] = CurrentMonth",
              "    )",
              "",
              "VAR PreviousMonthh = EDATE(CurrentMonth, -1)  // Calculate the previous month's date",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ US Sales],",
              "        dCalendar[Date] = PreviousMonthh",
              "    )",
              "",
              "VAR MoMPercentageChange = ",
              "    DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange),",
              "        BLANK(),",
              "        MoMPercentageChange",
              "    )"
            ],
            "lineageTag": "f297f03a-8347-4ef7-af2b-bb198c4e4384"
          },
          {
            "name": "# CM Total Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [$ Total Sales],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "1fb09922-66ab-499b-8b87-779ef85cc026"
          },
          {
            "name": "@ txt Simulation",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "\"Simulation: Decreasing shipping costs by \"&FORMAT([% Shiping Reduction Value],\"0%\")",
              "&\" could improve total revenue by \"&FORMAT([$ Saving Ship Changes],\"$0\")&\".\"",
              "& \" This would make your product more attractive to potential customers, especially price-sensitive ones, which could lead to an increase in the quantity of products sold.\""
            ],
            "lineageTag": "57d0bf35-e08f-4814-b082-bef5df0d967c"
          },
          {
            "name": "# PM Inter Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [$ International Sales],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "4d71c934-83b5-4e1d-9012-6a4ad5138c05"
          },
          {
            "name": "# PM Qty",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [# Qty Sold],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c32a6e38-c1f8-4834-9af9-dac07f86de82"
          },
          {
            "name": "# PM Orders",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [# Orders],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "555b6bd9-806e-49d7-ba2c-4dd605a6bffb"
          },
          {
            "name": "# CM Rating",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [# Avg. Rating],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "lineageTag": "018e0aa6-d6b1-43f0-9dec-deb0b72b583f"
          },
          {
            "name": "@ Min Max Color",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "VAR max_val = MAXX(ALLSELECTED(dCalendar[MonthAbbre], dCalendar[MonthNum]), [$ Total Sales])",
              "VAR min_val = MINX(ALLSELECTED(dCalendar[MonthAbbre], dCalendar[MonthNum]), [$ Total Sales])",
              "",
              "RETURN",
              "// Check if the measure is \"Total Sales YTD\" and exclude min/max coloring",
              "IF(ALLSELECTED('Analysis by'[Analysis by Fields]) = NAMEOF('Measuresss'[$ Total Sales YTD]), ",
              "    \"#CCCCCC\", // Default color for YTD bars",
              "    IF([$ Total Sales] = min_val, \"#FF4A4A\", ",
              "        IF([$ Total Sales] = max_val, \"#68DA52\", \"#CCCCCC\")",
              "    )",
              ")"
            ],
            "lineageTag": "af83964c-c7e7-41ff-add6-6f1f3a615b76"
          },
          {
            "name": "$ National Sales",
            "displayFolder": "$ Values",
            "expression": [
              "",
              "CALCULATE(",
              "    [$ Total Sales], ",
              "    Data[International Shipping] = \"No\"",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "ec5e3a75-1679-455f-a1ad-f4dfae2f857f"
          },
          {
            "name": "# CM National Sales",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [$ National Sales],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "f67b69b2-af3b-4929-90f8-540d0f260fbd"
          },
          {
            "name": "Area Sparkline Daily Avg Cpc",
            "displayFolder": "UI/UX",
            "expression": [
              "",
              "// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR LineColour = \"%239071ce\" ",
              "VAR PointColour = \"white\"",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>",
              "        <stop stop-color='#DBDBDB' offset='0' />",
              "        <stop stop-color='#DBDBDB' offset='0.3' />",
              "        <stop stop-color='white' offset='1' />",
              "    </linearGradient>",
              "</defs>\"",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN(dCalendar[StartMonth])",
              "VAR XMaxDate = MAX(dCalendar[StartMonth])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values(dCalendar[StartMonth]),CALCULATE([$ Total Sales]))",
              "VAR YMaxValue = MAXX(Values(dCalendar[StartMonth]),CALCULATE([$ Total Sales]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('dCalendar',dCalendar[StartMonth]),",
              "        \"X\",INT(150 * DIVIDE(dCalendar[StartMonth] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([$ Total Sales] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", dCalendar[StartMonth])",
              "",
              "// Last data points on the line",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, dCalendar[StartMonth] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, dCalendar[StartMonth] = XMaxDate), [X])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    --- gradient---",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" & Defs & ",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' ",
              "      stroke-width='0' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/>\" &",
              "    --- Lines---",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='3' points=' \" & Lines & ",
              "      \" '/>\" &",
              "    --- Last Point---",
              "        \"<circle cx='\"& LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='2' fill='\" & PointColour & \"' />\" &",
              "        \"</svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "924e6e76-0a5b-4a12-b163-b425ebd51e3b"
          },
          {
            "name": "@ Cor COndicional Canada Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales Canada]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "6f7cfbce-bd18-4597-9a58-f932b2e24c42"
          },
          {
            "name": "$ Total Shipping",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "$ Values",
            "expression": "Sum(Data[Shipping Charges])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "2680e707-67c5-4b28-8307-ca10cec9fdf7"
          },
          {
            "name": "# PM Shipping",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR LastDateInContext = MAX ( dCalendar[Date] )",
              "VAR PreviousMonthStart = EOMONTH ( LastDateInContext, -2 ) + 1",
              "VAR PreviousMonthEnd = EOMONTH ( LastDateInContext, -1 )",
              "RETURN",
              "CALCULATE (",
              "    [$ Shipping Charges],",
              "    dCalendar[Date] >= PreviousMonthStart &&",
              "    dCalendar[Date] <= PreviousMonthEnd",
              ")"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "d095757e-da5d-4171-aa51-6dbb0e081f8e"
          },
          {
            "name": "# QTY International",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(COUNTROWS(Data),FILTER(Data,Data[International Shipping]=\"Yes\"))",
            "formatString": "0.0",
            "lineageTag": "ee528676-e647-4348-89b1-04162af93874"
          },
          {
            "name": "# QTY Shippping",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(Data),",
              "       FILTER(",
              "        Data, ",
              "        Data[Shipping Charges] <> 0",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f2d49405-9186-4d92-b289-37401e253589"
          },
          {
            "name": "Selected Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "UI/UX",
            "expression": "Max(Data[Order Date]) ",
            "formatString": "d/m/yyyy",
            "lineageTag": "ce33d0ab-bfed-4cea-a3ed-c4e57c5f05d0"
          },
          {
            "name": "# Avg Price",
            "displayFolder": "# Numbers",
            "expression": "AVERAGE(Data[Sales Price])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "511a4d45-8e96-4510-b2fb-ce58c49d1629"
          },
          {
            "name": "# MoM Sales Change",
            "displayFolder": "# Numbers",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Total Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Total Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "RETURN",
              "    CurrentMonthSales - PreviousMonthSales"
            ],
            "formatString": "0",
            "lineageTag": "2825f90b-6d2d-4cc5-9299-c8f7c9156eff"
          },
          {
            "name": "MoM Sales % Change",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Total Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Total Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "RETURN",
              "    DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9d531416-88b6-4cc6-84a8-67fa67aee4f2"
          },
          {
            "name": "MoM Sales Growth",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = CALCULATE([$ Total Sales], DATESINPERIOD(dCalendar[Date], MAX(dCalendar[Date]), -1, MONTH))",
              "VAR PreviousMonthSales = CALCULATE([$ Total Sales], DATESINPERIOD(dCalendar[Date], MAX(dCalendar[Date]), -2, MONTH))",
              "RETURN",
              "    IF(",
              "        PreviousMonthSales <> 0,",
              "        (CurrentMonthSales - PreviousMonthSales) / PreviousMonthSales,",
              "        BLANK()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6c4f7a03-34bf-43ea-a20b-46a89ea53193"
          },
          {
            "name": "% MoM Sales % Change",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Total Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Total Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ Total Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "06c8c320-8141-4bea-a040-e2cf27b2972e"
          },
          {
            "name": "# Ranking Vendedor",
            "displayFolder": "# Numbers",
            "expression": "RANKX(ALL(Data),[$ Total Sales])",
            "formatString": "0",
            "lineageTag": "3aad84c7-1d96-4fb3-9f72-e14ec299be31"
          },
          {
            "name": "Least Popular Product",
            "expression": [
              "",
              "VAR WorstProduct =",
              "    TOPN(",
              "        1, ",
              "        FILTER(",
              "            VALUES('Data'[Product ID]), ",
              "            [$ Total Sales] > 0",
              "        ), ",
              "        [$ Total Sales], ",
              "        ASC",
              "    )",
              "RETURN",
              "    CONCATENATEX(",
              "        WorstProduct, ",
              "        'Data'[Product ID], ",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "9caadec9-7d22-4054-a8a3-664cd9e92965"
          },
          {
            "name": "% MoM International Sales % Change",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ International Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ International Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ International Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2f73e1e6-0d4b-47bf-b22a-4690805c561a"
          },
          {
            "name": "@ Cor COndicional Interntional Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM International Sales % Change]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "6b38eb88-b698-4d17-823e-d95bb3477950"
          },
          {
            "name": "% MoM Sales Australia",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Australia Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Australia Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ Australia Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "80940090-0207-4e79-9658-f9af607cc294"
          },
          {
            "name": "% MoM Sales Canada",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Canada Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Canada Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ Canada Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82d27621-7f18-4c39-9b98-6797f43cc043"
          },
          {
            "name": "% MoM Sales India",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ India Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ India Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ India Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5bf474a2-53b8-4893-903c-5235ced7ae46"
          },
          {
            "name": "% MoM Sales Europe",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ Europe Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ Europe Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ Europe Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "378a8348-4f34-4296-b0e3-0ada2ee9c7d5"
          },
          {
            "name": "% MoM Sales US",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [$ US Sales]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [$ US Sales],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [$ US Sales]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0.00,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "21b76167-2a81-40c9-a34f-533687c94a30"
          },
          {
            "name": "Past Month",
            "expression": [
              "",
              "    CALCULATE([$ Total Sales],",
              "        DATEADD(dCalendar[Date],",
              "        -1,",
              "        MONTH))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bd255ddc-5db1-4d36-9aca-72a324cfc5bb"
          },
          {
            "name": "% MoM Ship Charge",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [# PM Shipping]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [# PM Shipping],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [# PM Shipping]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8a52f1a4-0131-44b2-9f4d-b51d746111d7"
          },
          {
            "name": "@ Cor COndicional Ship Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Ship Charge]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "f95eab55-18ab-46f8-bfa6-f925abe7f890"
          },
          {
            "name": "% MoM Orders",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [# PM Orders]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [# PM Orders],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [# PM Orders]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "aee57336-0778-46ed-984c-49c41117ec45"
          },
          {
            "name": "% MoM Qty",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [# PM Qty]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [# PM Qty],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [# PM Qty]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6eedcb9b-5106-47bc-9af0-64e42f8116dc"
          },
          {
            "name": "% MoM Rating",
            "displayFolder": "% Percentage",
            "expression": [
              "",
              "VAR CurrentMonthSales = [# Avg. Rating]",
              "VAR PreviousMonthSales = ",
              "    CALCULATE(",
              "        [# Avg. Rating],",
              "        DATEADD(dCalendar[Date], -1, MONTH)",
              "    )",
              "VAR MoMPercentageChange = DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)",
              "VAR LastMonthMoMPercentageChangeCurrentYear = ",
              "    CALCULATE(",
              "        DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0),",
              "        LASTNONBLANK(dCalendar[Date], [# Avg. Rating]),",
              "        YEAR(dCalendar[Date]) = YEAR(TODAY())",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK(MoMPercentageChange) || MoMPercentageChange = 0,",
              "        LastMonthMoMPercentageChangeCurrentYear,",
              "        MoMPercentageChange",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "123d5e34-d8eb-4a11-9261-d02f141e5d76"
          },
          {
            "name": "@ Cor COndicional ORders Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Orders]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "0c899174-b08e-41b8-aad2-b3fd5c52acdc"
          },
          {
            "name": "@ Cor COndicional Qty Sales",
            "displayFolder": "% Percentage",
            "expression": "IF([% MoM Qty]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "99961d8f-9e9e-440f-81a9-ee4a3de74dd0"
          },
          {
            "name": "@ Cor COndicional Rating Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Rating]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "8628d784-a229-442a-8cf7-14e48b4ef8b6"
          },
          {
            "name": "@ Cor COndicional Total Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% Sales LM]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "db7f81b2-ec00-4bdd-a75e-70830b813e87"
          },
          {
            "name": "@ Cor COndicional US Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales US]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "328a585b-0439-4bb2-8edb-c363c97569f5"
          },
          {
            "name": "@ Cor COndicional Europe Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales Europe]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "41acf1d7-8f2f-4044-905d-12f4d5070ec6"
          },
          {
            "name": "# QTY US",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Quantity]),FILTER(Data,Data[Region]=\"US\"))",
            "formatString": "0",
            "lineageTag": "63848e97-882c-4683-b08d-78c5465dc54c"
          },
          {
            "name": "# QTY Europe",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Quantity]),FILTER(Data,Data[Region]=\"Europe\"))",
            "formatString": "0",
            "lineageTag": "1ec2616f-d180-4c5c-aaf8-b83cb3576774"
          },
          {
            "name": "# QTY AUstralia",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Quantity]),FILTER(Data,Data[Region]=\"Australia\"))",
            "formatString": "0",
            "lineageTag": "e60ba502-b6cb-490d-bc3f-c930f27d9ee3"
          },
          {
            "name": "# QTY Canada",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Quantity]),FILTER(Data,Data[Region]=\"Canada\"))",
            "formatString": "0",
            "lineageTag": "31a7dada-244d-45f2-bbb5-b0b2ca1d3eff"
          },
          {
            "name": "# QTY India",
            "displayFolder": "# Numbers",
            "expression": "CALCULATE(SUM(Data[Quantity]),FILTER(Data,Data[Region]=\"India\"))",
            "formatString": "0",
            "lineageTag": "33f634a2-d8e6-4ad7-a00e-fa3f917f23ad"
          },
          {
            "name": "@ Cor COndicional India Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales India]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "793a4e5c-b9b2-4c97-8ca2-5399cce7c4c4"
          },
          {
            "name": "@ Cor COndicional Australia Sales",
            "displayFolder": "UI/UX",
            "expression": "IF([% MoM Sales Australia]>0.01 , \"#68DA52\", \"#FF4A4A\")",
            "lineageTag": "cbdcce1d-e5f2-4818-80ad-47c8388f6042"
          },
          {
            "name": "@ txt Sales",
            "displayFolder": "UI/UX",
            "expression": "\"In comparison to the mean for 2024, the months of May (+23%), July (+18%), and March (+12%) emerge as notable deviations. August (-1%), September (+3%), and June (+0.7%) marginal dips indicate products to focus on.\"",
            "lineageTag": "80cf19dc-31ea-4898-82ea-c5c501c5de84"
          }
        ],
        "partitions": [
          {
            "name": "Measuresss",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Analysis by",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e30f890c431943ab93ae33951a961dac"
          }
        ],
        "columns": [
          {
            "name": "Analysis by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "74974b56-2bbd-43e8-b72a-fcfe652adf41",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Analysis by Fields"
                }
              ]
            },
            "sortByColumn": "Analysis by Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Analysis by Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e72dc233-8924-467a-a626-fdb05535e85a",
            "sortByColumn": "Analysis by Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Analysis by Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "be903aff-2bb5-4ed0-866a-83453241a9bb",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "903c86af-646d-42d6-b428-11fcf919a1a5",
        "partitions": [
          {
            "name": "Analysis by",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"MoM\", NAMEOF('Measuresss'[$ Total Sales]), 0),",
                "    (\"YTD\", NAMEOF('Measuresss'[$ Total Sales YTD]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "% Shiping Reduction",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6f85e39d62c7478490691b3189e193bc"
          }
        ],
        "columns": [
          {
            "name": "% Shiping Reduction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "2da4b3bd-aef0-43f4-88b8-0102579c9112",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6503082f-e89c-4011-b0a0-4d1510f44d35",
        "measures": [
          {
            "name": "% Shiping Reduction Value",
            "expression": "SELECTEDVALUE('% Shiping Reduction'[% Shiping Reduction], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "90edef3a-0cb1-4c40-b3af-b65861038def"
          }
        ],
        "partitions": [
          {
            "name": "% Shiping Reduction",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 0.41, 0.01)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}